---
title: '@yi2005bayesian'
author: "Frederick J. Boehm"
date: "12/10/2019"
output: github_document
bibliography: lit.bib
params:
  lastmod: !r lubridate::now()
---

Last modified: `r params$lastmod`.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Model

$$y = \mu + X\Gamma\beta + \epsilon$$

$\Gamma$ contains only zeroes and ones, to indicate 
which genomic loci affect the trait. The entire genome is partitioned into $H$ loci, and assume that the QTL 
can only occur at the $H$ loci.

For example, we might use the marker positions (with or without intermediate positions) as the loci. 

@yi2005bayes focus on at most $L$ loci, where $L << H$.

### Choosing $L$, upper bound on the number of QTL.

Assume that number of QTL, $l$, is Poisson with mean $l_0$, the prior expected number of QTL.

Then, choose $L$ such that $P(l > L) < \epsilon$, ie, the probability that $l$ is greater than $L$ is sufficiently small.

For example, one might use $L = l_0 + 3 \sqrt{l_0}$.

### Prior on $\gamma$

$\gamma$ is an indicator vector of length $H$. The $i^{th}$ entry is 1 if the $i^{th}$ locus is in the model.

$$p(\gamma) = \prod_j \left(w_j^{\gamma_j}(1 - w_j)^{1-\gamma_j} \right)$$

where $w_j = w_m$ or $w_j = w_e$, depending on whether it's a main effect or an epistatic effect. $w_m$ and $w_e$ are fixed hyperparameters. They say in the discussion section that one might put priors on them, too.






